name: Andres Crucetta
markdown: kramdown

external-image: true
picture: https://raw.githubusercontent.com/acrucetta/acrucetta.github.io/gh-pages/assets/images/IMG_0003%20(1).png

url: https://www.andrescn.me

collections:
  notes:
    output: true
  til:
    output: true
    permalink: /til/:name/
  til_topics:
    output: true
    permalink: /til/topic/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: []
      summary: ""
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      tags: []
      summary: ""
  - scope:
      path: ""
      type: til
    values:
      layout: til-entry
      tags: []
      summary: ""
  - scope:
      path: ""
      type: til_topics
    values:
      layout: til-topic
